config/routes.rb
Movieapp::Application.routes.draw do

  resources :posts

	match '/signin', :to => 'sessions#new'# Allows to put a link on a html pages
  get "sessions/new"

  get "sessions/create"

  match '/signout', :to => 'sessions#destroy'
  get "sessions/destroy"

  get "pages/home"

	match '/about' => 'pages#about'
  get "pages/about"

  resources :movies do
   resources :posts
  end

  resources :genres

  resources :users
  
  resources :sessions #Able to access the paths and routings for sessions

   root :to => 'pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movieapp</title>
  <%= stylesheet_link_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application", :media => "all" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
  <%= csrf_meta_tags %><!--This is a security feature-->
</head>
<body>
<div id="banner">
	<%= image_tag("The_Girl_With_The_Dragon_Tattoo.jpg", :size=> "100x50")%>
	<%= @page_title || "Movies We Love" %>
</div>

<div id="nav">
	<ul>
		<% if !signed_in? %>
			<li><%= link_to "Sign_In", signin_path %></li>
		<% else %>
			<li>Signed is as <%= @current_user.name%></li>
			<li><%= link_to "Sign Out", signout_path %></li>
		<% end %>
		<li><%= link_to "About", about_path%></li>
		<li><%= link_to "Movie News", 'http://oscar.go.com/nominees' %></li>
		<li><%=mail_to "mary.regan@dit.ie", "Contact Us"%></li>
		<li><%=link_to "Movies", movies_path %></li>
	</ul>
</div>
<%= yield %><!--The body of what ever page is yielded at this point. If you add two yield the content is put down twice on the page -->
<p id="notice"><%= notice %></p>
<h3> This website is for DT 354-3</h3>
</body>
</html>